import { CursorEvent } from '@/lib/types';

export const events: CursorEvent[] = [
	{
		id: 'cursor-coworking-day-guatemala',
		title: 'Cursor Coworking Day',
		titleLocal: 'Cursor Coworking Day Guatemala',
		date: '2026-08-01',
		displayDate: '1 de agosto de 2026',
		displayDates: { en: 'August 1, 2026', es: '1 de agosto de 2026' },
		time: '09:00 – 18:00',
		capacity: 75,
		location: 'Campus Tec · Mountain View · Nivel 2 · Salón 204, Ciudad de Guatemala',
		description:
			'Un día completo para developers, founders y builders que construyen con IA: charlas, coworking, lightning talks, mentoring y comunidad en un solo espacio.',
		descriptions: {
			en: 'A full day for developers, founders, and builders who create with AI: talks, coworking, lightning talks, mentoring, and community in one space.',
			es: 'Un día completo para developers, founders y builders que construyen con IA: charlas, coworking, lightning talks, mentoring y comunidad en un solo espacio.',
		},
		lumaUrl: 'https://luma.com/cursor-xxan',
		thumbnail: '/events/cursor-coworking-day-gt.png',
		galleryImages: [
			'/events/cursor-coworking-day-gt.png',
			'/events/cursor-coworking-day-marvin.png',
		],
		status: 'upcoming',
		host: {
			name: 'DDR Innova',
			logo: '/images/partners/ddr.png',
			url: 'https://ddrinnova.com',
		},
		agenda: [
			{
				time: '09:00',
				title: 'Doors Open & Check-in',
				description: 'Registro, bienvenida, café y setup de workspace. Espacio de bienvenida con fotografía e impresoras térmicas.',
			},
			{
				time: '09:30',
				title: 'Apertura — ¿Por qué estamos aquí?',
				description: 'Contexto rápido del mundo tech con IA y por qué Guatemala debe participar. Incluye AI Speed Networking.',
			},
			{
				time: '10:00',
				title: 'Charla 1 — Dominando Cursor / Del Contexto a la Acción',
				speaker: 'Sael Developer',
			},
			{
				time: '10:20',
				title: 'Bloque 1 — Lightning Talks',
				description: 'Espacio abierto para compartir lo que estás construyendo u opiniones sobre IA (5–7 min).',
			},
			{
				time: '11:00',
				title: 'Charla 2 — Harness your Agent',
				description: 'Una breve historia de la evolución del desarrollo agéntico.',
				speaker: 'Jordi Dimas',
			},
			{
				time: '11:35',
				title: 'Bloque 2 — Lightning Talks',
				description: 'Continuación del open floor.',
			},
			{
				time: '12:00',
				title: 'Charla 3 — De Developer a AI Builder',
				description: 'Lo que aprendí construyendo con IA desde Guatemala.',
				speaker: 'Marvin Mazariegos',
			},
			{
				time: '12:30',
				title: 'Bloque 3 — Lightning Talks',
				description: 'Continuación del open floor.',
			},
			{
				time: '13:00',
				title: 'Almuerzo + Networking',
				description: 'Dinámica de comida, board games y Kahoot de IA.',
			},
			{
				time: '14:00',
				title: 'Lightning Talks',
				description: 'Espacio abierto para que asistentes compartan con la comunidad.',
			},
			{
				time: '14:30',
				title: 'Charla 4 — Misión: Certifícate',
				description: 'Consejos prácticos para perderle el miedo a las certificaciones tech.',
				speaker: 'Diego Cum',
			},
			{
				time: '15:15',
				title: 'Lightning Talks — Bloque B',
			},
			{
				time: '15:45',
				title: 'Charla 5 — Agentes con superpoderes',
				description: 'Cómo pasar de un modelo de IA a un agente de IA.',
				speaker: 'Diego Rosales',
			},
			{
				time: '16:15',
				title: 'Lightning Talks — Bloque C',
			},
			{
				time: '16:30',
				title: 'Build & Share',
				description: 'Comparte lo que construiste durante el día: tools, agentes, proyectos o experimentos.',
			},
			{
				time: '17:15',
				title: 'Community Closing',
				description: 'Agradecimientos, takeaways del día y reconocimiento a speakers y participantes.',
			},
			{
				time: '17:35',
				title: 'Próximos pasos',
				description: 'Meetups futuros, comunidad Discord/WhatsApp e invitación a speakers.',
			},
			{
				time: '17:45',
				title: 'Foto oficial + Networking final',
				description: 'Foto grupal y tiempo libre para intercambiar contactos.',
			},
		],
	},
	{
		id: 'cursor-meetup-antigua',
		title: 'Cursor Meetup Antigua',
		titleLocal: 'Cursor Meetup Antigua Guatemala',
		date: '2026-03-22',
		displayDate: '22 de marzo de 2026',
		displayDates: { en: 'March 22, 2026', es: '22 de marzo de 2026' },
		location: 'Antigua Guatemala',
		recapPath: '/recaps/cursor-meetup-antigua',
		thumbnail: '/events/antigua-cursor-gt-1.jpeg',
		galleryImages: [
			'/events/antigua-cursor-gt-2.jpeg',
			'/events/antigua-cursor-gt-3.jpeg',
			'/events/antigua-cursor-gt-4.jpeg',
			'/events/antigua-cursor-gt-5.jpeg',
			'/events/antigua-cursor-gt-6.jpeg',
			'/events/antigua-cursor-gt-7.jpeg',
			'/events/antigua-cursor-gt-8.jpeg',
			'/events/antigua-cursor-gt-9.jpeg',
			'/events/antigua-cursor-gt-10.jpeg',
			'/events/antigua-cursor-gt-11.jpeg',
		],
		status: 'past',
		host: {
			name: 'El Cubo Center',
			logo: '/images/partners/el-cubo-center.svg',
			url: 'https://elcubocenter.com',
		},
	},
	{
		id: 'cursor-hackathon-guatemala',
		title: 'Cursor Hackathon Guatemala',
		titleLocal: 'Cursor Hackathon Guatemala 2026',
		date: '2026-03-07',
		displayDate: '7 de marzo de 2026',
		displayDates: { en: 'March 7, 2026', es: '7 de marzo de 2026' },
		attendees: 140,
		location: 'Universidad del Valle de Guatemala, Ciudad de Guatemala',
		recapPath: '/recaps/cursor-hackathon-guatemala',
		thumbnail: '/events/cursor-hackathon-gt-1.jpeg',
		galleryImages: [
			'/events/cursor-hackathon-gt-2.jpeg',
			'/events/cursor-hackathon-gt-3.jpeg',
			'/events/cursor-hackathon-gt-4.jpeg',
		],
		status: 'past',
		host: {
			name: 'Universidad del Valle de Guatemala',
			logo: '/images/partners/uvg.svg',
			url: 'https://www.uvg.edu.gt',
		},
	},
	{
		id: 'cafe-cursor-guatemala',
		title: 'Cafe Cursor Guatemala',
		titleLocal: 'Cafe Cursor Guatemala',
		date: '2025-12-13',
		displayDate: '13 de diciembre de 2025',
		displayDates: { en: 'December 13, 2025', es: '13 de diciembre de 2025' },
		location: 'Ciudad de Guatemala, Guatemala',
		recapPath: '/recaps/cafe-cursor-guatemala',
		thumbnail: '/events/cafe-cursor-gt-1.jpeg',
		galleryImages: [
			'/events/cafe-cursor-gt-2.jpeg',
			'/events/cafe-cursor-gt-3.jpeg',
			'/events/cafe-cursor-gt-4.jpeg',
			'/events/cafe-cursor-gt-5.jpeg',
			'/events/cafe-cursor-gt-6.jpeg',
			'/events/cafe-cursor-gt-7.jpeg',
			'/events/cafe-cursor-gt-8.jpeg',
			'/events/cafe-cursor-gt-9.jpeg',
			'/events/cafe-cursor-gt-10.jpeg',
			'/events/cafe-cursor-gt-11.jpeg',
		],
		status: 'past',
	},
	{
		id: 'first-cursor-meetup-guatemala',
		title: 'First Cursor Meetup Guatemala',
		titleLocal: 'Primer Meetup de Cursor en Guatemala',
		date: '2025-08-31',
		displayDate: '31 de agosto de 2025',
		displayDates: { en: 'August 31, 2025', es: '31 de agosto de 2025' },
		location: 'Ciudad de Guatemala, Guatemala',
		recapPath: '/recaps/first-cursor-meetup',
		thumbnail: '/events/primer-meetup-cursor-gt-1.jpeg',
		galleryImages: [
			'/events/primer-meetup-cursor-gt-2.jpeg',
			'/events/primer-meetup-cursor-gt-3.jpeg',
			'/events/primer-meetup-cursor-gt-4.jpeg',
		],
		status: 'past',
	},
];

export const upcomingEvents = events.filter((event) => event.status === 'upcoming');
export const pastEvents = events.filter((event) => event.status === 'past');
